package Frame.Registration;

import Frame.Login.LoginFrame;
import User.Vendor;
import javax.swing.JOptionPane;

/**
 *
 * @author CHOK QI YANG TP070091
 */
public class VendorRegistration extends javax.swing.JFrame {
    
    public VendorRegistration() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrationPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblStoreName = new javax.swing.JLabel();
        lblStoreLocation = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblServiceType = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txtStoreName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnBackToLogin = new javax.swing.JButton();
        lblFoodCategory = new javax.swing.JLabel();
        lblRestaurantAddress = new javax.swing.JLabel();
        chkDelivery = new javax.swing.JCheckBox();
        chkTakeAway = new javax.swing.JCheckBox();
        chkDineIn = new javax.swing.JCheckBox();
        cbxCuisine = new javax.swing.JComboBox<>();
        scrollRestaurantAddress = new javax.swing.JScrollPane();
        txtRestaurantAddress = new javax.swing.JTextPane();
        lblStoreNameError = new javax.swing.JLabel();
        lblStoreLocationError = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        lblPhoneError = new javax.swing.JLabel();
        lblServiceError = new javax.swing.JLabel();
        lblCuisineError = new javax.swing.JLabel();
        lblAddressError = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        lblConfirmPasswordError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendor Registration");
        setMinimumSize(new java.awt.Dimension(800, 500));

        registrationPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Vendor Registration");

        lblStoreName.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblStoreName.setText("*Store Name:");

        lblStoreLocation.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblStoreLocation.setText("*Store Location:");

        lblEmailAddress.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblEmailAddress.setText("*Email Address:");

        lblPhoneNumber.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblPhoneNumber.setText("*Phone Number:");

        lblServiceType.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblServiceType.setText("*Service Type:");

        lblPassword.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblPassword.setText("*Password:");

        lblConfirmPassword.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblConfirmPassword.setText("*Confirm Password:");

        txtStoreName.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtStoreName.setToolTipText("Cannot be empty.");

        txtLocation.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtLocation.setText("e.g., Asia Pacific Unversity");
        txtLocation.setToolTipText("Input the university of your restaurant.");

        txtEmailAddress.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtEmailAddress.setToolTipText("Must include '@' and '.com'");

        txtPhoneNumber.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtPhoneNumber.setText("e.g., 0362621111");
        txtPhoneNumber.setToolTipText("Follow this format: '0362621111'");

        txtPassword.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtPassword.setToolTipText("Do not leave this empty.");

        txtConfirmPassword.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtConfirmPassword.setToolTipText("Make sure the passwords are identical.");

        btnRegister.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnBackToLogin.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnBackToLogin.setText("Back to Login");
        btnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLoginActionPerformed(evt);
            }
        });

        lblFoodCategory.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblFoodCategory.setText("*Cuisine:");

        lblRestaurantAddress.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblRestaurantAddress.setText("*Restaurant Address:");

        chkDelivery.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        chkDelivery.setText("Delivery");

        chkTakeAway.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        chkTakeAway.setText("Take Away");

        chkDineIn.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        chkDineIn.setText("Dine-in");

        cbxCuisine.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        cbxCuisine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "American", "Chinese", "Japanese", "Korean", "Thai", "Vietnamese", "Indian", "Italian", "Mexican", "Mediterranean", "Middle Eastern", "Mexican", "Brazilian", "Peruvian", "Argentinian", "French", "German", "Spanish", "Greek", "British", "Others", "African", "Caribbean", "Vegetarian/Vegan", "Seafood", "BBQ/Grill", "Fast Food", "Pizza", "Burgers", "Sandwiches", "Desserts", "Coffee/Tea", "Ice Cream/Frozen Yogurt", "Bakery", "Sushi", "Health Food", "Gluten-Free", "Kosher", "Halal", "Food Trucks", "Street Food", "Asian Fusion", "Tex-Mex" }));
        cbxCuisine.setToolTipText("Select a cuisine that best describe your restaurant.");
        cbxCuisine.setMinimumSize(new java.awt.Dimension(98, 29));
        cbxCuisine.setPreferredSize(new java.awt.Dimension(98, 29));

        txtRestaurantAddress.setToolTipText("Do not leave this empty.");
        scrollRestaurantAddress.setViewportView(txtRestaurantAddress);

        lblStoreNameError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblStoreNameError.setForeground(new java.awt.Color(204, 0, 51));

        lblStoreLocationError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblStoreLocationError.setForeground(new java.awt.Color(204, 0, 51));

        lblEmailError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblEmailError.setForeground(new java.awt.Color(204, 0, 51));

        lblPhoneError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblPhoneError.setForeground(new java.awt.Color(204, 0, 51));

        lblServiceError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblServiceError.setForeground(new java.awt.Color(204, 0, 51));

        lblCuisineError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblCuisineError.setForeground(new java.awt.Color(204, 0, 51));

        lblAddressError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblAddressError.setForeground(new java.awt.Color(204, 0, 51));

        lblPasswordError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(204, 0, 51));

        lblConfirmPasswordError.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        lblConfirmPasswordError.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStoreName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStoreLocation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblServiceType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFoodCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRestaurantAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConfirmPassword)
                    .addComponent(txtStoreName)
                    .addComponent(txtLocation)
                    .addComponent(txtEmailAddress)
                    .addComponent(txtPhoneNumber)
                    .addComponent(txtPassword)
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxCuisine, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(registrationPanelLayout.createSequentialGroup()
                                .addComponent(chkDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkTakeAway)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDineIn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollRestaurantAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStoreNameError)
                    .addComponent(lblStoreLocationError)
                    .addComponent(lblEmailError)
                    .addComponent(lblPhoneError)
                    .addComponent(lblServiceError)
                    .addComponent(lblCuisineError)
                    .addComponent(lblAddressError)
                    .addComponent(lblPasswordError)
                    .addComponent(lblConfirmPasswordError))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStoreName)
                            .addComponent(txtStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStoreNameError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStoreLocation)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStoreLocationError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailAddress)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNumber)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblServiceType)
                            .addComponent(chkDelivery)
                            .addComponent(chkTakeAway)
                            .addComponent(chkDineIn)
                            .addComponent(lblServiceError))
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFoodCategory)
                            .addComponent(cbxCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCuisineError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollRestaurantAddress)
                            .addGroup(registrationPanelLayout.createSequentialGroup()
                                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRestaurantAddress)
                                    .addComponent(lblAddressError))
                                .addGap(0, 77, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPasswordError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfirmPassword)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConfirmPasswordError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void clearErrorLabels() {
        lblStoreNameError.setText("");
        lblStoreLocationError.setText("");
        lblEmailError.setText("");
        lblPhoneError.setText("");
        lblServiceError.setText("");
        lblCuisineError.setText("");
        lblAddressError.setText("");
        lblPasswordError.setText("");
        lblConfirmPasswordError.setText("");
    }
    
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        clearErrorLabels();
        
        String name = txtStoreName.getText();
        String location = txtLocation.getText();
        String emailAddress = txtEmailAddress.getText();
        String phoneNumber = txtPhoneNumber.getText();
        
        String services = "";
        if (chkDelivery.isSelected()) {
            services += "Delivery, ";
        }
        if (chkTakeAway.isSelected()) {
            services += "Take Away, ";
        }
        if (chkDineIn.isSelected()) {
            services += "Dine-in, ";
        }
        
        String cuisine = cbxCuisine.getSelectedItem().toString();
        String restaurantAddress = txtRestaurantAddress.getText();
        String password = txtPassword.getText();
        String confirmPassword = txtConfirmPassword.getText();
        
        int error = 0;
        
        if (name.isEmpty()) {
            lblStoreNameError.setText("Invalid store name");
            error++;
        }
        if (location.isEmpty()) {
            lblStoreLocationError.setText("Invalid store location");
            error++;
        }
        if (emailAddress.isEmpty() || !emailAddress.contains("@") || !emailAddress.contains(".com")) {
            lblEmailError.setText("Invalid email address");
            error++;
        }
        if (phoneNumber.isEmpty() || phoneNumber.length() != 10) {
            lblPhoneError.setText("Invalid phone number");
            error++;
        }
        if (!chkDelivery.isSelected() && !chkTakeAway.isSelected() && !chkDineIn.isSelected()) {
            lblServiceError.setText("Choose at least one service type");
            error++;
        }
        if (restaurantAddress.isEmpty()) {
            lblAddressError.setText("Invalid restaurant address");
        }
        if (password.isEmpty()) {
            lblPasswordError.setText("Invalid password");
            error++;
        } else if (confirmPassword.isEmpty()){
            lblConfirmPasswordError.setText("Please confirm your password");
            error++;
        } else if (!password.equals(confirmPassword)){
            lblConfirmPasswordError.setText("Make sure both passwords are identical");
            error++;
        }
        
        if (error == 0) {
            services = services.substring(0, services.length() - 2);
            Vendor newVendor = new Vendor(name, emailAddress, phoneNumber, password, cuisine, services, location, restaurantAddress);
            Boolean dataRecordResults = newVendor.recordData("Pending Users");
            
            if (dataRecordResults == true) {
                JOptionPane.showMessageDialog(this, "Sign-up successful.");
                btnBackToLogin.doClick();
            } else {
                JOptionPane.showMessageDialog(this, "Sign-up unsuccessful. Please try again.");
            }
        }
        
    }//GEN-LAST:event_btnRegisterActionPerformed
 
    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        dispose();
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VendorRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cbxCuisine;
    private javax.swing.JCheckBox chkDelivery;
    private javax.swing.JCheckBox chkDineIn;
    private javax.swing.JCheckBox chkTakeAway;
    private javax.swing.JLabel lblAddressError;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblConfirmPasswordError;
    private javax.swing.JLabel lblCuisineError;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblFoodCategory;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblPhoneError;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblRestaurantAddress;
    private javax.swing.JLabel lblServiceError;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JLabel lblStoreLocation;
    private javax.swing.JLabel lblStoreLocationError;
    private javax.swing.JLabel lblStoreName;
    private javax.swing.JLabel lblStoreNameError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JScrollPane scrollRestaurantAddress;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextPane txtRestaurantAddress;
    private javax.swing.JTextField txtStoreName;
    // End of variables declaration//GEN-END:variables
}
