package Panel.Admin;

import Transaction.Wallet;
import User.Customer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHENG WEI QUAN TP071634
 */
public class CreateCustomer extends javax.swing.JPanel {
    private final DefaultTableModel modelCustomerCreate = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column){  
            return false;  
        }
    };
    private final String[] customerColumn = {"Pending ID", "Name", "Gender", "Phone Number", "Email Address"};
    private Customer selectedCustomer;
    
    public CreateCustomer() {
        initComponents(); 
        modelCustomerCreate.setColumnIdentifiers(customerColumn);
        tableCustomer.setModel(modelCustomerCreate);
        displayPendingCustomers();
    }
    
    public final void displayPendingCustomers() {
        btnApproveCustomer.setEnabled(false);
        btnRejectCustomer.setEnabled(false);
        
        selectedCustomer = null;
        modelCustomerCreate.setRowCount(0);
        
        Customer customers = new Customer();
        ArrayList<Customer> customerList = customers.getCustomerList(true);
        
        if (!customerList.isEmpty()) {
            for (Customer pendingCustomer : customerList) {
                String[] tableData = {pendingCustomer.getId(), pendingCustomer.getName(), pendingCustomer.getGender(),
                    pendingCustomer.getPhoneNumber(), pendingCustomer.getEmailAddress()};
                modelCustomerCreate.addRow(tableData);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTableCustomer = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        btnRejectCustomer = new javax.swing.JButton();
        btnApproveCustomer = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(944, 600));
        setMinimumSize(new java.awt.Dimension(944, 600));
        setPreferredSize(new java.awt.Dimension(944, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCustomer.setModel(modelCustomerCreate);
        tableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableCustomerMouseReleased(evt);
            }
        });
        scrollTableCustomer.setViewportView(tableCustomer);

        add(scrollTableCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 470));

        btnRejectCustomer.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 21)); // NOI18N
        btnRejectCustomer.setText("Reject");
        btnRejectCustomer.setEnabled(false);
        btnRejectCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectCustomerActionPerformed(evt);
            }
        });
        add(btnRejectCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 140, 50));

        btnApproveCustomer.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 21)); // NOI18N
        btnApproveCustomer.setText("Approve");
        btnApproveCustomer.setEnabled(false);
        btnApproveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveCustomerActionPerformed(evt);
            }
        });
        add(btnApproveCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 140, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRejectCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectCustomerActionPerformed
        if (selectedCustomer != null) {
            if (selectedCustomer.removePendingUser()) {
                JOptionPane.showMessageDialog(this, "Customer registration rejected.");
            } else {
                JOptionPane.showMessageDialog(this, "Unable to reject customer registration. Please try again.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a pending customer form the table to reject their registration.");
        }
        displayPendingCustomers();
    }//GEN-LAST:event_btnRejectCustomerActionPerformed

    private void btnApproveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveCustomerActionPerformed
        if (selectedCustomer != null) {
            selectedCustomer.removePendingUser();
            
            selectedCustomer.setId(selectedCustomer.generateCustomerID());
            selectedCustomer.getUserLogin().setId(selectedCustomer.getId());
            selectedCustomer.setCustomerWallet(new Wallet());
            
            if (selectedCustomer.createUser()) {
                JOptionPane.showMessageDialog(this, "Customer registration successful.");
            } else {
                JOptionPane.showMessageDialog(this, "Customer registration unsuccessful. Please try again.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a pending customer form the table to register them.");
        }
        displayPendingCustomers();
    }//GEN-LAST:event_btnApproveCustomerActionPerformed

    private void tableCustomerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomerMouseReleased
        int row = tableCustomer.getSelectedRow();
        if (row >= 0) {
            String id = String.valueOf(tableCustomer.getValueAt(row, 0));
            selectedCustomer = new Customer(id).getUser(true);
            
            btnApproveCustomer.setEnabled(true);
            btnRejectCustomer.setEnabled(true);
        } else {
            btnApproveCustomer.setEnabled(false);
            btnRejectCustomer.setEnabled(false);
        }
    }//GEN-LAST:event_tableCustomerMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveCustomer;
    private javax.swing.JButton btnRejectCustomer;
    private javax.swing.JScrollPane scrollTableCustomer;
    private javax.swing.JTable tableCustomer;
    // End of variables declaration//GEN-END:variables
}
