/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel.Admin;
/**
 *
 * @author Dixon
 */
public class CreateUserPanel extends javax.swing.JPanel {
  
    public CreateUserPanel() {
        initComponents();
    }
    
    public void displayPendingUsers() {
        TabbedPane.setSelectedIndex(0);
        createCustomer.displayPendingCustomers();
        createDeliveryRunner.displayPendingDeliveryRunners();
        createVendor.displayPendingVendors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        createCustomer = new Panel.Admin.CreateCustomer();
        createDeliveryRunner = new Panel.Admin.CreateDeliveryRunner();
        createVendor = new Panel.Admin.CreateVendor();

        setMaximumSize(new java.awt.Dimension(944, 600));
        setMinimumSize(new java.awt.Dimension(944, 600));

        TabbedPane.setMaximumSize(new java.awt.Dimension(944, 600));
        TabbedPane.setMinimumSize(new java.awt.Dimension(944, 600));
        TabbedPane.setPreferredSize(new java.awt.Dimension(944, 600));
        TabbedPane.addTab("Pending Customer", createCustomer);
        TabbedPane.addTab("Pending Delivery Runner", createDeliveryRunner);
        TabbedPane.addTab("Pending Vendor", createVendor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabbedPane.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane TabbedPane;
    private Panel.Admin.CreateCustomer createCustomer;
    private Panel.Admin.CreateDeliveryRunner createDeliveryRunner;
    private Panel.Admin.CreateVendor createVendor;
    // End of variables declaration//GEN-END:variables
}
