package Panel.Admin;


import Review.VendorReview;
import User.Vendor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHENG WEI QUAN TP071634
 */
public class FeedbackVendor extends javax.swing.JPanel {
    private final DefaultTableModel modelVendorFeedback = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    private final String[] vendorColumn = {"ID", "Name", "Average Rating"};
    
    public FeedbackVendor() {
        initComponents();
        modelVendorFeedback.setColumnIdentifiers(vendorColumn);
        tableVendorReview.setModel(modelVendorFeedback);
        displayVendorReviews();
    }

    public final void displayVendorReviews() {
        txtVendorReviews.setText("");
        modelVendorFeedback.setRowCount(0);
        
        Vendor vendors = new Vendor();
        ArrayList<Vendor> vendorList = vendors.getVendorList(false);
        
        if (!vendorList.isEmpty()) {
            for (Vendor vendor : vendorList) {
                VendorReview review = new VendorReview(vendor);
                String[] tableData = {vendor.getId(), vendor.getName(), review.getAverageRating()};
                modelVendorFeedback.addRow(tableData);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneVendor1 = new javax.swing.JScrollPane();
        tableVendorReview = new javax.swing.JTable();
        lblVendorReviews = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVendorReviews = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableVendorReview.setModel(modelVendorFeedback);
        tableVendorReview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableVendorReviewMouseReleased(evt);
            }
        });
        jScrollPaneVendor1.setViewportView(tableVendorReview);

        add(jScrollPaneVendor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 540));

        lblVendorReviews.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblVendorReviews.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVendorReviews.setText("Reviews");
        add(lblVendorReviews, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 360, -1));

        txtVendorReviews.setColumns(20);
        txtVendorReviews.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVendorReviews.setLineWrap(true);
        txtVendorReviews.setText("Select a vendor to view their reviews.");
        txtVendorReviews.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtVendorReviews);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 360, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void tableVendorReviewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVendorReviewMouseReleased
        int row = tableVendorReview.getSelectedRow();
        if (row >= 0) {
            String reviewString = "";
            String id = String.valueOf(tableVendorReview.getValueAt(row, 0));
            Vendor vendor = (Vendor) new Vendor(id).getUser(false);
            
            VendorReview reviews = new VendorReview(vendor);
            ArrayList<VendorReview> reviewList = reviews.getVendorReviewList();
            
            if (!reviewList.isEmpty()) {
                for (VendorReview review : reviewList) {
                    reviewString += review.getId()+" - "+review.getReviewDate() + " - " + review.getReviewRating() + "\n" + review.getReviewComments() + 
                            "\n------------------------------------------------\n";
                }
            }
            txtVendorReviews.setText(reviewString);
        } else {
            txtVendorReviews.setText("Select a runner to view their food and service reviews.");
        }
    }//GEN-LAST:event_tableVendorReviewMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneVendor1;
    private javax.swing.JLabel lblVendorReviews;
    private javax.swing.JTable tableVendorReview;
    private javax.swing.JTextArea txtVendorReviews;
    // End of variables declaration//GEN-END:variables
}
