package Panel.DeliveryRunner;

import Frame.UserFrames.DeliveryRunnerMainPage;
import User.DeliveryRunner;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author NABIL BIN NAZME NAZIM TP072131
 */
public class MainPanel extends javax.swing.JPanel {
    private final CardLayout mainPanelLayout;

    public MainPanel() {
        initComponents();
        this.setLayout(new CardLayout());
        mainPanelLayout = (CardLayout) this.getLayout();
        add(currentTaskPanel, "currentTaskPanel");
        add(profilePanel, "profilePanel");
        add(notificationPanel, "notificationPanel");
        add(earningsPanel, "earningsPanel");
        add(reviewPanel, "reviewPanel");
    }
    
    public void updateDeliveryRunner(DeliveryRunner deliveryRunner) {
        DeliveryRunnerMainPage userFrame = (DeliveryRunnerMainPage) SwingUtilities.getWindowAncestor(this);
        userFrame.setDeliveryRunner(deliveryRunner);
    }
    
    public void displayProfile(DeliveryRunner deliveryRunner) {
        profilePanel.displayProfile(deliveryRunner);
        mainPanelLayout.show(this, "profilePanel");
    }
    
    public void displayCurrentTask(DeliveryRunner deliveryRunner) {
        currentTaskPanel.displayCurrentTask(deliveryRunner);
        mainPanelLayout.show(this, "currentTaskPanel");
    }
    
    public void displayEarningsPanel(DeliveryRunner deliveryRunner){
        earningsPanel.displayRevenueDashboard(deliveryRunner);
        mainPanelLayout.show(this, "earningsPanel");
    }
    
    public void displayDeliveryReviews(DeliveryRunner deliveryRunner){
        reviewPanel.displayDeliveryReviews(deliveryRunner);
        mainPanelLayout.show(this, "reviewPanel");
    }
    
    public void displayNotification(DeliveryRunner runner){
        notificationPanel.displayNotifications(runner);
        mainPanelLayout.show(this, "notificationPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentTaskPanel = new Panel.DeliveryRunner.CurrentTaskPanel();
        profilePanel = new Panel.DeliveryRunner.ProfilePanel();
        notificationPanel = new Panel.DeliveryRunner.NotificationPanel();
        reviewPanel = new Panel.DeliveryRunner.ReviewPanel();
        earningsPanel = new Panel.DeliveryRunner.EarningsPanel();

        setMaximumSize(new java.awt.Dimension(880, 600));
        setMinimumSize(new java.awt.Dimension(880, 600));
        setPreferredSize(new java.awt.Dimension(880, 600));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.CardLayout());
        add(currentTaskPanel, "card2");
        add(profilePanel, "card3");
        add(notificationPanel, "card4");
        add(reviewPanel, "card5");
        add(earningsPanel, "card6");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.DeliveryRunner.CurrentTaskPanel currentTaskPanel;
    private Panel.DeliveryRunner.EarningsPanel earningsPanel;
    private Panel.DeliveryRunner.NotificationPanel notificationPanel;
    private Panel.DeliveryRunner.ProfilePanel profilePanel;
    private Panel.DeliveryRunner.ReviewPanel reviewPanel;
    // End of variables declaration//GEN-END:variables
}
