package Panel.DeliveryRunner;

import Review.DeliveryReview;
import User.DeliveryRunner;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NABIL BIN NAZME NAZIM TP072131
 */
public class ReviewPanel extends javax.swing.JPanel {
    private final DefaultTableModel reviewTableModel = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    private final String[] deliveryReviewsColumns = {"Delivery ID", "Review Date", "Review Rating"};
    
    private DeliveryReview deliveryReview;
    
    public ReviewPanel() {
        initComponents();
        reviewTableModel.setColumnIdentifiers(deliveryReviewsColumns);
        deliveryReviewTable.setModel(reviewTableModel);
    }
    
    public void displayDeliveryReviews(DeliveryRunner runner) {
        reviewTableModel.setRowCount(0);
        this.deliveryReview = null;
        clearReviewDetails();
        DeliveryReview reviews = new DeliveryReview(runner);
        
        ArrayList<DeliveryReview> reviewList = reviews.getDeliveryReviewList();
        for (DeliveryReview review : reviewList) {
            String[] tableData = {review.getId(), review.getReviewDate(), String.valueOf(review.getReviewRating())};
            reviewTableModel.addRow(tableData);
        }
    }
    
    private void displayDeliveryReviewDetails() {
        if (deliveryReview != null) {
            lblReviewID.setText(deliveryReview.getId());
            lblReviewDate.setText(deliveryReview.getReviewDate());
            lblReviewRating.setText(String.valueOf(deliveryReview.getReviewRating()));
            lblReviewCcomments.setText(deliveryReview.getReviewComments());
        }
    }
    
    private void clearReviewDetails() {
        lblReviewID.setText("");
        lblReviewDate.setText("");
        lblReviewRating.setText("");
        lblReviewCcomments.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRevenueDashboard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliveryReviewTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblReviewID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblReviewDate = new javax.swing.JTextField();
        lblReviewRating = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblReviewCcomments = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(880, 600));
        setMinimumSize(new java.awt.Dimension(880, 600));
        setPreferredSize(new java.awt.Dimension(880, 600));

        lblRevenueDashboard.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblRevenueDashboard.setText("Delivery Reviews");

        deliveryReviewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deliveryReviewTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(deliveryReviewTable);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblReviewID.setEditable(false);
        lblReviewID.setBackground(new java.awt.Color(255, 255, 255));
        lblReviewID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReviewID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblReviewID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblReviewID.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Review ID:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Review Comments:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Review Rating:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Review Date:");

        lblReviewDate.setEditable(false);
        lblReviewDate.setBackground(new java.awt.Color(255, 255, 255));
        lblReviewDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReviewDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblReviewDate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblReviewDate.setEnabled(false);

        lblReviewRating.setEditable(false);
        lblReviewRating.setBackground(new java.awt.Color(255, 255, 255));
        lblReviewRating.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReviewRating.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblReviewRating.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblReviewRating.setEnabled(false);

        lblReviewCcomments.setColumns(20);
        lblReviewCcomments.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReviewCcomments.setLineWrap(true);
        lblReviewCcomments.setRows(5);
        lblReviewCcomments.setWrapStyleWord(true);
        lblReviewCcomments.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblReviewCcomments.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblReviewCcomments.setEnabled(false);
        jScrollPane2.setViewportView(lblReviewCcomments);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReviewDate)
                            .addComponent(lblReviewRating)
                            .addComponent(lblReviewID))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblReviewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblReviewDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblReviewRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRevenueDashboard)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRevenueDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliveryReviewTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryReviewTableMouseReleased
        int row = deliveryReviewTable.getSelectedRow();
        if (row >= 0) {
            String reviewID = String.valueOf(deliveryReviewTable.getValueAt(row, 0));
            deliveryReview = new DeliveryReview(reviewID).getReview(false);
            displayDeliveryReviewDetails();
        }
    }//GEN-LAST:event_deliveryReviewTableMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable deliveryReviewTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRevenueDashboard;
    private javax.swing.JTextArea lblReviewCcomments;
    private javax.swing.JTextField lblReviewDate;
    private javax.swing.JTextField lblReviewID;
    private javax.swing.JTextField lblReviewRating;
    // End of variables declaration//GEN-END:variables
}
