package Panel.Customer;

import Order.DeliveryTask;
import Order.Order;
import Review.DeliveryReview;
import Review.VendorReview;
import User.Customer;
import Time.Time;
import javax.swing.JOptionPane;

/**
 *
 * @author CHOK QI YANG TP070091
 */
public class GiveReviewPanel extends javax.swing.JPanel {
    private Customer customer;
    private DeliveryTask task;
    private Order order;
    
    public GiveReviewPanel() {
        initComponents();
    }
    
    public void displayReviewFeedback(Customer customer, Order order) {
        this.customer = customer;
        this.order = order;
        task = null;
        
        lblVendorName.setText(order.getVendor().getName());
        lblDate.setText(order.getOrderDate());
        lblService.setText(order.getServiceType());
        
        if (order.getServiceType().equals("Delivery")) {
            DeliveryTask deliveryTask = new DeliveryTask();
            deliveryTask.setOrder(order);
            task = (DeliveryTask) deliveryTask.getDeliveryTask(true);
            try {
                if (task.getDeliveryID() != null) {
                    deliveryReviewPanel.setVisible(true);
                }
            } catch (NullPointerException e) {
                deliveryReviewPanel.setVisible(false);
            }
        } else {
            deliveryReviewPanel.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider3 = new javax.swing.JSlider();
        vendorReviewPanel = new javax.swing.JPanel();
        lblVendorReview = new javax.swing.JLabel();
        lblRestaurantName = new javax.swing.JLabel();
        lblVendorName = new javax.swing.JLabel();
        lblVendorComments = new javax.swing.JLabel();
        lblVendorRating = new javax.swing.JLabel();
        lblServiceType = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        sliderVendorRating = new javax.swing.JSlider();
        scrollVendorComments = new javax.swing.JScrollPane();
        txtVendorComments = new javax.swing.JTextArea();
        lblVendorOptional = new javax.swing.JLabel();
        lblProvideReview = new javax.swing.JLabel();
        deliveryReviewPanel = new javax.swing.JPanel();
        lblDeliveryReview = new javax.swing.JLabel();
        lblDeliveryComments = new javax.swing.JLabel();
        lblDeliveryRating = new javax.swing.JLabel();
        sliderDeliveryRating = new javax.swing.JSlider();
        sliderDeliveryComments = new javax.swing.JScrollPane();
        txtDeliveryComments = new javax.swing.JTextArea();
        lblDeliveryOptional = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(906, 580));
        setMinimumSize(new java.awt.Dimension(906, 580));
        setPreferredSize(new java.awt.Dimension(906, 580));

        vendorReviewPanel.setBackground(new java.awt.Color(255, 255, 255));
        vendorReviewPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        vendorReviewPanel.setMaximumSize(new java.awt.Dimension(445, 530));
        vendorReviewPanel.setMinimumSize(new java.awt.Dimension(445, 530));

        lblVendorReview.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblVendorReview.setText("Vendor Review");

        lblRestaurantName.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblRestaurantName.setText("Restaurant Name:");

        lblVendorName.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblVendorName.setText("{Insert Name}");

        lblVendorComments.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblVendorComments.setText("Comments:");

        lblVendorRating.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblVendorRating.setText("Rating:");

        lblServiceType.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblServiceType.setText("Service Type:");

        lblOrderDate.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblOrderDate.setText("Order Date:");

        lblService.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblService.setText("{Insert Name}");

        lblDate.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblDate.setText("{Insert Name}");

        sliderVendorRating.setMajorTickSpacing(1);
        sliderVendorRating.setMaximum(5);
        sliderVendorRating.setMinimum(1);
        sliderVendorRating.setPaintLabels(true);
        sliderVendorRating.setPaintTicks(true);
        sliderVendorRating.setSnapToTicks(true);

        txtVendorComments.setColumns(20);
        txtVendorComments.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtVendorComments.setLineWrap(true);
        txtVendorComments.setRows(5);
        txtVendorComments.setTabSize(4);
        txtVendorComments.setWrapStyleWord(true);
        txtVendorComments.setMaximumSize(new java.awt.Dimension(292, 164));
        txtVendorComments.setMinimumSize(new java.awt.Dimension(292, 164));
        scrollVendorComments.setViewportView(txtVendorComments);

        lblVendorOptional.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblVendorOptional.setText("(optional)");

        javax.swing.GroupLayout vendorReviewPanelLayout = new javax.swing.GroupLayout(vendorReviewPanel);
        vendorReviewPanel.setLayout(vendorReviewPanelLayout);
        vendorReviewPanelLayout.setHorizontalGroup(
            vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                .addGroup(vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblVendorRating))
                    .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblVendorReview, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblRestaurantName)
                        .addGap(6, 6, 6)
                        .addComponent(lblVendorName))
                    .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblServiceType)
                        .addGap(6, 6, 6)
                        .addComponent(lblService))
                    .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblOrderDate)
                        .addGap(6, 6, 6)
                        .addComponent(lblDate))
                    .addGroup(vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vendorReviewPanelLayout.createSequentialGroup()
                            .addGroup(vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(lblVendorOptional))
                                .addComponent(lblVendorComments, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(12, 12, 12)
                            .addComponent(scrollVendorComments, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(sliderVendorRating, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vendorReviewPanelLayout.setVerticalGroup(
            vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblVendorReview)
                .addGap(6, 6, 6)
                .addGroup(vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendorName)
                    .addComponent(lblRestaurantName))
                .addGap(6, 6, 6)
                .addGroup(vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServiceType)
                    .addComponent(lblService))
                .addGap(6, 6, 6)
                .addGroup(vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderDate)
                    .addComponent(lblDate))
                .addGap(8, 8, 8)
                .addGroup(vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(sliderVendorRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVendorRating))
                .addGap(18, 18, 18)
                .addGroup(vendorReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorReviewPanelLayout.createSequentialGroup()
                        .addComponent(lblVendorComments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVendorOptional)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendorReviewPanelLayout.createSequentialGroup()
                        .addComponent(scrollVendorComments, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        lblProvideReview.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblProvideReview.setText("Provide Review");

        deliveryReviewPanel.setBackground(new java.awt.Color(255, 255, 255));
        deliveryReviewPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        deliveryReviewPanel.setMaximumSize(new java.awt.Dimension(445, 530));
        deliveryReviewPanel.setMinimumSize(new java.awt.Dimension(445, 530));
        deliveryReviewPanel.setPreferredSize(new java.awt.Dimension(445, 530));

        lblDeliveryReview.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblDeliveryReview.setText("Delivery Review");

        lblDeliveryComments.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblDeliveryComments.setText("Comments:");

        lblDeliveryRating.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblDeliveryRating.setText("Rating:");

        sliderDeliveryRating.setMajorTickSpacing(1);
        sliderDeliveryRating.setMaximum(5);
        sliderDeliveryRating.setMinimum(1);
        sliderDeliveryRating.setPaintLabels(true);
        sliderDeliveryRating.setPaintTicks(true);
        sliderDeliveryRating.setSnapToTicks(true);

        txtDeliveryComments.setColumns(20);
        txtDeliveryComments.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtDeliveryComments.setLineWrap(true);
        txtDeliveryComments.setRows(5);
        txtDeliveryComments.setTabSize(4);
        txtDeliveryComments.setWrapStyleWord(true);
        txtDeliveryComments.setMaximumSize(new java.awt.Dimension(292, 164));
        txtDeliveryComments.setMinimumSize(new java.awt.Dimension(292, 164));
        sliderDeliveryComments.setViewportView(txtDeliveryComments);

        lblDeliveryOptional.setFont(new java.awt.Font("Dubai Light", 0, 16)); // NOI18N
        lblDeliveryOptional.setText("(optional)");

        javax.swing.GroupLayout deliveryReviewPanelLayout = new javax.swing.GroupLayout(deliveryReviewPanel);
        deliveryReviewPanel.setLayout(deliveryReviewPanelLayout);
        deliveryReviewPanelLayout.setHorizontalGroup(
            deliveryReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryReviewPanelLayout.createSequentialGroup()
                .addGroup(deliveryReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryReviewPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDeliveryReview, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryReviewPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(deliveryReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDeliveryRating)
                            .addComponent(lblDeliveryComments)
                            .addComponent(lblDeliveryOptional))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(deliveryReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderDeliveryRating, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sliderDeliveryComments, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        deliveryReviewPanelLayout.setVerticalGroup(
            deliveryReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryReviewPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblDeliveryReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deliveryReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderDeliveryRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeliveryRating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deliveryReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryReviewPanelLayout.createSequentialGroup()
                        .addComponent(lblDeliveryComments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDeliveryOptional))
                    .addComponent(sliderDeliveryComments, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSubmit.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProvideReview)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vendorReviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deliveryReviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblProvideReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryReviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vendorReviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtVendorComments.setText("");
        txtDeliveryComments.setText("");
        sliderVendorRating.setValue(5);
        sliderDeliveryRating.setValue(5);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Time time = new Time();
        String reviewDate = time.getDate();
        
        String vendorComments = txtVendorComments.getText();
        int vendorRating = sliderVendorRating.getValue();
        VendorReview vendorReview = new VendorReview(order.getOrderID(), vendorComments, reviewDate, vendorRating,
        order.getVendor());
        
        DeliveryReview deliveryReview = null;
        
        if (deliveryReviewPanel.isVisible()) {
            String deliveryComments = txtDeliveryComments.getText();
            int deliveryRating = sliderDeliveryRating.getValue();
            deliveryReview = new DeliveryReview(task.getDeliveryID(), deliveryComments, reviewDate, deliveryRating, 
            task.getDeliveryRunner());
        }
        
        if (deliveryReview != null) {
            if (vendorReview.writeReview(true) && deliveryReview.writeReview(false)) {
                JOptionPane.showMessageDialog(this, "Review submission successful.");
            } else {
                JOptionPane.showMessageDialog(this, "Review submission unsuccessful.");
            }
        } else {
            if (vendorReview.writeReview(true)) {
                JOptionPane.showMessageDialog(this, "Review submission successful.");
            } else {
                JOptionPane.showMessageDialog(this, "Review submission unsuccessful.");
            }
        }
        HistoryPanel historyPanel = (HistoryPanel) this.getParent();
        historyPanel.displayOrderHistory(customer);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        btnClear.doClick();
        HistoryPanel historyPanel = (HistoryPanel) this.getParent();
        historyPanel.displayOrderHistory(customer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel deliveryReviewPanel;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDeliveryComments;
    private javax.swing.JLabel lblDeliveryOptional;
    private javax.swing.JLabel lblDeliveryRating;
    private javax.swing.JLabel lblDeliveryReview;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblProvideReview;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JLabel lblVendorComments;
    private javax.swing.JLabel lblVendorName;
    private javax.swing.JLabel lblVendorOptional;
    private javax.swing.JLabel lblVendorRating;
    private javax.swing.JLabel lblVendorReview;
    private javax.swing.JScrollPane scrollVendorComments;
    private javax.swing.JScrollPane sliderDeliveryComments;
    private javax.swing.JSlider sliderDeliveryRating;
    private javax.swing.JSlider sliderVendorRating;
    private javax.swing.JTextArea txtDeliveryComments;
    private javax.swing.JTextArea txtVendorComments;
    private javax.swing.JPanel vendorReviewPanel;
    // End of variables declaration//GEN-END:variables
}
