package Panel.Customer;

import Order.Order;
import User.Customer;
import java.awt.CardLayout;

/**
 *
 * @author CHOK QI YANG TP070091
 */
public class HistoryPanel extends javax.swing.JPanel {
    public final CardLayout historyPanelLayout;
    
    public HistoryPanel() {
        initComponents();
        this.setLayout(new CardLayout());
        historyPanelLayout = (CardLayout) this.getLayout();
        this.add(tabbedPane, "tabbedPane");
        this.add(giveReviewPanel, "giveReviewPanel");
    }
    
    public void displayOrderHistory(Customer customer) {
        tabbedPane.setSelectedIndex(0);
        refreshPanels(customer);
        historyPanelLayout.show(this, "tabbedPane");
    }
    
    public void displayTransactionHistory(Customer customer) {
        tabbedPane.setSelectedIndex(1);
        refreshPanels(customer);
        historyPanelLayout.show(this, "tabbedPane");
    }
    
    public void displayReview(Customer customer, Order order) {
        giveReviewPanel.displayReviewFeedback(customer, order);
        historyPanelLayout.show(this, "giveReviewPanel");
    }
    
    private void refreshPanels(Customer customer) {
        orderHistoryPanel.displayOrderHistory(customer);
        transactionHistoryPanel.displayTransactionHistory(customer);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        orderHistoryPanel = new Panel.Customer.OrderHistoryPanel();
        transactionHistoryPanel = new Panel.Customer.TransactionHistoryPanel();
        giveReviewPanel = new Panel.Customer.GiveReviewPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(906, 580));
        setMinimumSize(new java.awt.Dimension(906, 580));
        setPreferredSize(new java.awt.Dimension(906, 580));
        setLayout(new java.awt.CardLayout());

        tabbedPane.setMaximumSize(new java.awt.Dimension(906, 580));
        tabbedPane.setMinimumSize(new java.awt.Dimension(906, 580));
        tabbedPane.setPreferredSize(new java.awt.Dimension(906, 580));
        tabbedPane.addTab("Order History", orderHistoryPanel);
        tabbedPane.addTab("Transaction History", transactionHistoryPanel);

        add(tabbedPane, "card2");
        add(giveReviewPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.Customer.GiveReviewPanel giveReviewPanel;
    private Panel.Customer.OrderHistoryPanel orderHistoryPanel;
    public javax.swing.JTabbedPane tabbedPane;
    private Panel.Customer.TransactionHistoryPanel transactionHistoryPanel;
    // End of variables declaration//GEN-END:variables
}
