package Panel.Customer;

import User.Customer;

/**
 *
 * @author CHOK QI YANG TP070091
 */
public class OrderPanel extends javax.swing.JPanel {
    
    public OrderPanel() {
        initComponents();
    }
    
    public void displayCurrentOrder(Customer customer) {
        tabbedPane.setSelectedIndex(0);
        refreshPanels(customer);
    }
    
    public void displayDineInOrder(Customer customer) {
        tabbedPane.setSelectedIndex(1);
        refreshPanels(customer);
    }
    
    private void refreshPanels(Customer customer) {
        currentOrderPanel.displayCurrentOrder(customer);
        dineInOrderPanel.displayDineInOrders(customer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        currentOrderPanel = new Panel.Customer.CurrentOrderPanel();
        dineInOrderPanel = new Panel.Customer.DineInOrderPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(906, 580));
        setMinimumSize(new java.awt.Dimension(906, 580));
        setPreferredSize(new java.awt.Dimension(906, 580));
        setLayout(new java.awt.CardLayout());

        tabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPane.setMaximumSize(new java.awt.Dimension(926, 600));
        tabbedPane.setMinimumSize(new java.awt.Dimension(926, 600));
        tabbedPane.setPreferredSize(new java.awt.Dimension(926, 600));
        tabbedPane.addTab("Current Order", currentOrderPanel);
        tabbedPane.addTab("Dine-in Order", dineInOrderPanel);

        add(tabbedPane, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.Customer.CurrentOrderPanel currentOrderPanel;
    private Panel.Customer.DineInOrderPanel dineInOrderPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
