package Panel.Customer;

import Transaction.TopUp;
import User.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author CHOK QI YANG TP070091
 */
public class ProfilePanel extends javax.swing.JPanel {
    private Customer customer;
    private TopUp topUp;
    
    public ProfilePanel() {
        initComponents();
        btnSave.setVisible(false);
    }
    
    public void displayProfile(Customer customer) {
        this.customer = customer;
        clearErrorLabels();
        txtPassword.setEchoChar('*');
        
        txtName.setText(customer.getName());
        txtPhoneNumber.setText(customer.getPhoneNumber());
        txtEmailAddress.setText(customer.getEmailAddress());
        lblGenderType.setText(customer.getGender());
        txtPassword.setText(customer.getUserLogin().getPassword());
        
        txtName.setEnabled(false);
        txtPhoneNumber.setEnabled(false);
        txtEmailAddress.setEnabled(false);
        txtPassword.setEnabled(false);
    }
    
    
    public void displayTopUp() {
        lblCreditAmount.setText("RM "+String.format("%.2f", customer.getCustomerWallet().getCurrentCreditAmount()));
        
        txtTopUpAmount.setText("");
        lblDate.setText("");
        lblTime.setText("");
        lblAmount.setText("");
        
        topUp = (TopUp) new TopUp(customer).getObject("Pending Top-up");
        
        if (topUp != null) {
            lblStatus.setText(topUp.getTopUpStatus());
            lblDate.setText(topUp.getTopUpDate());
            lblTime.setText(topUp.getTopUpTime());
            lblAmount.setText("RM "+String.format("%.2f", topUp.getTopUpAmount()));
            txtTopUpAmount.setEnabled(false);
            btnRequest.setEnabled(false);
        } else {
            lblStatus.setText("No Requests");
            txtTopUpAmount.setEnabled(true);
            btnRequest.setEnabled(true);
        }
    }
    
    public void clearErrorLabels() {
        lblNameError.setText("");
        lblEmailError.setText("");
        lblPhoneError.setText("");
        lblPasswordError.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrationPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnEdit = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblPhoneError = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lblGenderType = new javax.swing.JLabel();
        lblCustomerRegistration1 = new javax.swing.JLabel();
        btnDeliveryAddress = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTopUp = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCreditAmount2 = new javax.swing.JLabel();
        lblStatusLabel = new javax.swing.JLabel();
        lblRequestedDate = new javax.swing.JLabel();
        lblRequestedTime = new javax.swing.JLabel();
        lblRequestedAmount = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblCreditAmount = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtTopUpAmount = new javax.swing.JTextField();
        lblTopUpAmount = new javax.swing.JLabel();
        lblTopUpCredits = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        lblRM = new javax.swing.JLabel();
        lblCurrentAmount = new javax.swing.JLabel();

        registrationPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 580));
        setMinimumSize(new java.awt.Dimension(900, 580));
        setPreferredSize(new java.awt.Dimension(900, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSave.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtPassword.setToolTipText("Setting a more complex password will help protect you!");
        txtPassword.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPassword.setEnabled(false);

        btnEdit.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblNameError.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(204, 0, 51));

        lblName.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblName.setText("Name:");

        lblEmailError.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblEmailError.setForeground(new java.awt.Color(204, 0, 51));

        lblEmailAddress.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblEmailAddress.setText("Email Address:");

        lblPhoneError.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblPhoneError.setForeground(new java.awt.Color(204, 0, 51));

        lblPhoneNumber.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblPhoneNumber.setText("Phone Number:");

        lblPasswordError.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(204, 0, 51));

        lblGender.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblGender.setText("Gender:");

        lblPassword.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblPassword.setText("Password:");

        txtName.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtName.setEnabled(false);

        txtEmailAddress.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtEmailAddress.setToolTipText("Must include '@' and '.com'");
        txtEmailAddress.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEmailAddress.setEnabled(false);

        txtPhoneNumber.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtPhoneNumber.setToolTipText("e.g., 0161118888");
        txtPhoneNumber.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPhoneNumber.setEnabled(false);

        lblGenderType.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblGenderType.setText("{Insert Gender}");

        lblCustomerRegistration1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblCustomerRegistration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerRegistration1.setText("Profile");

        btnDeliveryAddress.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnDeliveryAddress.setText("Delivery Addresses");
        btnDeliveryAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCustomerRegistration1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(lblName)
                                .addGap(12, 12, 12)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lblNameError))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(lblPassword)
                                .addGap(12, 12, 12)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lblPasswordError))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lblGender)
                                .addGap(12, 12, 12)
                                .addComponent(lblGenderType))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblPhoneNumber)
                                .addGap(12, 12, 12)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lblPhoneError))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lblEmailAddress)
                                .addGap(12, 12, 12)
                                .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lblEmailError))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeliveryAddress)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustomerRegistration1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblNameError))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmailAddress)
                            .addComponent(lblEmailError))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNumber)
                            .addComponent(lblPhoneError))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(lblGenderType))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblPasswordError))))
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnDeliveryAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(346, 574));
        jPanel2.setMinimumSize(new java.awt.Dimension(346, 574));
        jPanel2.setPreferredSize(new java.awt.Dimension(346, 574));

        lblTopUp.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblTopUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopUp.setText("Top-up");

        lblCreditAmount2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblCreditAmount2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCreditAmount2.setText("Pending Top-up");

        lblStatusLabel.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblStatusLabel.setText("Status:");

        lblRequestedDate.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblRequestedDate.setText("Requested Date:");

        lblRequestedTime.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblRequestedTime.setText("Requested Time");

        lblRequestedAmount.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblRequestedAmount.setText("Requested Amount:");

        btnRefresh.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblStatus.setText("{Insert Status}");

        lblDate.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N

        lblTime.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N

        lblAmount.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreditAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRequestedDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRequestedTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRequestedAmount, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(lblDate)
                            .addComponent(lblTime)
                            .addComponent(lblAmount))))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreditAmount2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusLabel)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestedDate)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestedTime)
                    .addComponent(lblTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestedAmount)
                    .addComponent(lblAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCreditAmount.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblCreditAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCreditAmount.setText("{Credit}");

        txtTopUpAmount.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtTopUpAmount.setToolTipText("Must include '@' and '.com'");

        lblTopUpAmount.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblTopUpAmount.setText("Top-up Amount:");

        lblTopUpCredits.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTopUpCredits.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTopUpCredits.setText("Top-up Credits:");

        btnRequest.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        lblRM.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblRM.setText("RM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTopUpAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTopUpAmount))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTopUpCredits)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopUpCredits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTopUpAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTopUpAmount)
                    .addComponent(lblRM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCurrentAmount.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        lblCurrentAmount.setText("Current Amount:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblCurrentAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTopUp)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditAmount)
                    .addComponent(lblCurrentAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        btnSave.setVisible(true);
        txtName.setEnabled(true);
        txtPhoneNumber.setEnabled(true);
        txtEmailAddress.setEnabled(true);
        txtPassword.setEnabled(true);
         txtPassword.setEchoChar('\0');
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        clearErrorLabels();
        
        String name = txtName.getText();
        String emailAddress = txtEmailAddress.getText();
        String phoneNumber = txtPhoneNumber.getText();
        
        String password = txtPassword.getText();
        
        int error = 0;

        if (name.isEmpty()) {
            lblNameError.setText("Invalid name");
            error++;
        }
        if (emailAddress.isEmpty() || !emailAddress.contains("@") || !emailAddress.contains(".com")) {
            lblEmailError.setText("Invalid email address");
            error++;
        }
        if (phoneNumber.isEmpty() || phoneNumber.length() != 10) {
            lblPhoneError.setText("Invalid phone number");
            error++;
        }
        if (password.isEmpty()) {
            lblPasswordError.setText("Invalid password");
            error++;
        }
        
        if (error == 0) {
            customer.setName(name);
            customer.setPhoneNumber(phoneNumber);
            customer.setEmailAddress(emailAddress);
            customer.updatePassword(password);
            
            customer.getUserLogin().updateData("Login");
            if (customer.updateData("Customer") == true) {
                JOptionPane.showMessageDialog(this, "Update successful.");
                btnSave.setVisible(false);
                displayProfile(customer);
                
                MainPanel parent = (MainPanel) getParent();
                parent.updateCustomer(customer);
                
            } else {
                JOptionPane.showMessageDialog(this, "Update unsuccessful. Please try again.");
            }
        }
        displayProfile(customer);
        btnSave.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        String amount = txtTopUpAmount.getText();
        
        try {
            double topUpAmount = Double.parseDouble(amount);
            topUp = new TopUp(customer, topUpAmount);
            if (topUp.requestTopUp()) {
                JOptionPane.showMessageDialog(this, "Top-up request successful.");
                txtTopUpAmount.setText("");
                btnRefresh.doClick();
            } else {
                JOptionPane.showMessageDialog(this, "Top-up request unsuccessful. Please try again.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a numeric number. Please try again.");
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        displayTopUp();
        if (lblStatus.getText().equals("No Requests")) {
            btnRequest.setEnabled(true);
            txtTopUpAmount.setEnabled(true);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeliveryAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryAddressActionPerformed
        SetDeliveryAddressFrame deliveryAddressFrame = new SetDeliveryAddressFrame();
        deliveryAddressFrame.displayDeliveryAddresses(customer);
        deliveryAddressFrame.setVisible(true);
    }//GEN-LAST:event_btnDeliveryAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeliveryAddress;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCreditAmount;
    private javax.swing.JLabel lblCreditAmount2;
    private javax.swing.JLabel lblCurrentAmount;
    private javax.swing.JLabel lblCustomerRegistration1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGenderType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblPhoneError;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblRM;
    private javax.swing.JLabel lblRequestedAmount;
    private javax.swing.JLabel lblRequestedDate;
    private javax.swing.JLabel lblRequestedTime;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusLabel;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTopUp;
    private javax.swing.JLabel lblTopUpAmount;
    private javax.swing.JLabel lblTopUpCredits;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtTopUpAmount;
    // End of variables declaration//GEN-END:variables
}
