package Frame.Login;

import Frame.Registration.*;
import User.*;

/**
 *
 * @author CHOK QI YANG TP070091
 */
public class LoginFrame extends javax.swing.JFrame {

    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        loginPanel = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtID = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        chkShowPassword = new javax.swing.JCheckBox();
        lblRegister = new javax.swing.JLabel();
        lblRegisterCustomer = new javax.swing.JLabel();
        lblRegisterDeliveryRunner = new javax.swing.JLabel();
        lblRegisterVendor = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 400));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        loginPanel.setMinimumSize(new java.awt.Dimension(600, 400));

        lblLogin.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblLogin.setText("Login");

        lblPassword.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        lblPassword.setText("Password:");

        lblID.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        lblID.setText("ID:");

        txtPassword.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        txtPassword.setMaximumSize(new java.awt.Dimension(351, 48));
        txtPassword.setMinimumSize(new java.awt.Dimension(351, 48));
        txtPassword.setPreferredSize(new java.awt.Dimension(351, 48));
        txtPassword.setSelectionColor(new java.awt.Color(204, 204, 204));

        txtID.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        txtID.setMaximumSize(new java.awt.Dimension(351, 48));
        txtID.setMinimumSize(new java.awt.Dimension(351, 48));
        txtID.setPreferredSize(new java.awt.Dimension(351, 48));
        txtID.setSelectionColor(new java.awt.Color(204, 204, 204));

        btnLogin.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setMaximumSize(new java.awt.Dimension(100, 48));
        btnLogin.setMinimumSize(new java.awt.Dimension(100, 48));
        btnLogin.setPreferredSize(new java.awt.Dimension(100, 48));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        chkShowPassword.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        chkShowPassword.setText("Show");
        chkShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPasswordActionPerformed(evt);
            }
        });

        lblRegister.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lblRegister.setText("Not Signed Up? Register Here!");
        lblRegister.setMaximumSize(new java.awt.Dimension(220, 30));
        lblRegister.setMinimumSize(new java.awt.Dimension(220, 30));
        lblRegister.setPreferredSize(new java.awt.Dimension(220, 30));

        lblRegisterCustomer.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lblRegisterCustomer.setForeground(new java.awt.Color(0, 51, 255));
        lblRegisterCustomer.setText("New Customer");
        lblRegisterCustomer.setMaximumSize(new java.awt.Dimension(105, 30));
        lblRegisterCustomer.setMinimumSize(new java.awt.Dimension(105, 30));
        lblRegisterCustomer.setPreferredSize(new java.awt.Dimension(105, 30));
        lblRegisterCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterCustomerMouseClicked(evt);
            }
        });

        lblRegisterDeliveryRunner.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lblRegisterDeliveryRunner.setForeground(new java.awt.Color(0, 51, 255));
        lblRegisterDeliveryRunner.setText("New Delivery Runner");
        lblRegisterDeliveryRunner.setMaximumSize(new java.awt.Dimension(145, 30));
        lblRegisterDeliveryRunner.setMinimumSize(new java.awt.Dimension(145, 30));
        lblRegisterDeliveryRunner.setPreferredSize(new java.awt.Dimension(145, 30));
        lblRegisterDeliveryRunner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterDeliveryRunnerMouseClicked(evt);
            }
        });

        lblRegisterVendor.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lblRegisterVendor.setForeground(new java.awt.Color(0, 51, 255));
        lblRegisterVendor.setText("New Vendor");
        lblRegisterVendor.setMaximumSize(new java.awt.Dimension(90, 30));
        lblRegisterVendor.setMinimumSize(new java.awt.Dimension(90, 30));
        lblRegisterVendor.setPreferredSize(new java.awt.Dimension(90, 30));
        lblRegisterVendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterVendorMouseClicked(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setMaximumSize(new java.awt.Dimension(220, 30));
        lblError.setMinimumSize(new java.awt.Dimension(220, 30));
        lblError.setPreferredSize(new java.awt.Dimension(220, 30));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblRegisterVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRegisterDeliveryRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRegisterCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(lblLogin))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblID)
                                    .addComponent(lblPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkShowPassword))
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisterVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterDeliveryRunner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String id = txtID.getText();
        String password = txtPassword.getText();
        
        Login login = new Login(id, password);
        
        String loginValidationResults = login.validateLogin();
        
        if (!id.isEmpty() && !password.isEmpty()) {
            switch (loginValidationResults) {
                case "Incorrect" -> lblError.setText("Incorrect ID or password. Please try again.");
                case "Admin" -> {
                    Admin admin = new Admin(id);
                    admin = (Admin) admin.getObject("Admin");
                    dispose();
                    admin.login();
                }
                case "Customer" -> {
                    Customer customer = new Customer(id);
                    customer = (Customer) customer.getObject("Customer");
                    dispose();
                    customer.login();
                }
                case "Vendor" -> {
                    Vendor vendor = new Vendor(id);
                    vendor = (Vendor) vendor.getObject("Vendor");
                    dispose();
                    vendor.login();
                }
                case "Delivery Runner" -> {
                    DeliveryRunner runner = new DeliveryRunner(id);
                    runner = (DeliveryRunner) runner.getObject("Delivery Runner");
                    dispose();
                    runner.login();
                }
                default -> lblError.setText("User does not exist. Please try again."); 
            }
        } else {
            lblError.setText("Invalid ID or password. Please try again.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        if (chkShowPassword.isSelected()) {
            txtPassword.setEchoChar('\0');
        } else {
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowPasswordActionPerformed

    private void lblRegisterVendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterVendorMouseClicked
        VendorRegistration vendorRegisterFrame = new VendorRegistration();
        dispose();
        vendorRegisterFrame.setVisible(true);
    }//GEN-LAST:event_lblRegisterVendorMouseClicked

    private void lblRegisterDeliveryRunnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterDeliveryRunnerMouseClicked
        DeliveryRunnerRegistration deliveryRunnerRegisterFrame = new DeliveryRunnerRegistration();
        dispose();
        deliveryRunnerRegisterFrame.setVisible(true);
    }//GEN-LAST:event_lblRegisterDeliveryRunnerMouseClicked

    private void lblRegisterCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterCustomerMouseClicked
        CustomerRegistration customerRegisterFrame = new CustomerRegistration();
        dispose();
        customerRegisterFrame.setVisible(true);
    }//GEN-LAST:event_lblRegisterCustomerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRegisterCustomer;
    private javax.swing.JLabel lblRegisterDeliveryRunner;
    private javax.swing.JLabel lblRegisterVendor;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
