package Frame.UserFrames;

import Frame.Login.LoginFrame;
import Review.DeliveryReview;
import User.DeliveryRunner;

/**
 *
 * @author NABIL BIN NAZME NAZIM TP072131
 */
public class DeliveryRunnerMainPage extends javax.swing.JFrame {
    private DeliveryRunner deliveryRunner;
    
    public DeliveryRunnerMainPage(DeliveryRunner deliveryRunner) {
        initComponents();
        setLocationRelativeTo(null);
        this.deliveryRunner = deliveryRunner;
        
        lblDeliveryRunnerName.setText(deliveryRunner.getName());
        DeliveryReview deliveryReview = new DeliveryReview(deliveryRunner);
        lblRatingAmount.setText(deliveryReview.getAverageRating());
        mainPanel.displayCurrentTask(deliveryRunner);
    }

    private DeliveryRunnerMainPage() {
    }
   
    public void setDeliveryRunner(DeliveryRunner deliveryRunner) {
        this.deliveryRunner = deliveryRunner;
        lblDeliveryRunnerName.setText(deliveryRunner.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        btnTask = new javax.swing.JButton();
        lblDeliveryRunnerName = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        btnDelilveryRunnerProfile = new javax.swing.JButton();
        btnEarnings = new javax.swing.JButton();
        lblRating = new javax.swing.JLabel();
        lblRatingAmount = new javax.swing.JLabel();
        btnReadReview = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnNotification = new javax.swing.JButton();
        mainPanel = new Panel.DeliveryRunner.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delivery Runner Main Menu");
        setMaximumSize(new java.awt.Dimension(1200, 600));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setSize(new java.awt.Dimension(1200, 600));

        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sidePanel.setPreferredSize(new java.awt.Dimension(274, 565));

        btnTask.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnTask.setText("Task");
        btnTask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTask.setMaximumSize(new java.awt.Dimension(123, 60));
        btnTask.setMinimumSize(new java.awt.Dimension(123, 60));
        btnTask.setPreferredSize(new java.awt.Dimension(123, 60));
        btnTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskActionPerformed(evt);
            }
        });

        lblDeliveryRunnerName.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblDeliveryRunnerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeliveryRunnerName.setText("DeliveryRunner1");

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/UserFrames/profileicon.png"))); // NOI18N

        btnDelilveryRunnerProfile.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnDelilveryRunnerProfile.setText("Profile");
        btnDelilveryRunnerProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelilveryRunnerProfile.setMaximumSize(new java.awt.Dimension(123, 60));
        btnDelilveryRunnerProfile.setMinimumSize(new java.awt.Dimension(123, 60));
        btnDelilveryRunnerProfile.setPreferredSize(new java.awt.Dimension(123, 60));
        btnDelilveryRunnerProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelilveryRunnerProfileActionPerformed(evt);
            }
        });

        btnEarnings.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnEarnings.setText("Earnings");
        btnEarnings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEarnings.setMaximumSize(new java.awt.Dimension(123, 60));
        btnEarnings.setMinimumSize(new java.awt.Dimension(123, 60));
        btnEarnings.setPreferredSize(new java.awt.Dimension(123, 60));
        btnEarnings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEarningsActionPerformed(evt);
            }
        });

        lblRating.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblRating.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRating.setText("Rating:");

        lblRatingAmount.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblRatingAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRatingAmount.setText("No Reviews");

        btnReadReview.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        btnReadReview.setText("Read Reviews");
        btnReadReview.setMaximumSize(new java.awt.Dimension(123, 60));
        btnReadReview.setMinimumSize(new java.awt.Dimension(123, 60));
        btnReadReview.setPreferredSize(new java.awt.Dimension(123, 60));
        btnReadReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadReviewActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out ");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnNotification.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnNotification.setText("Notification");
        btnNotification.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNotification.setMaximumSize(new java.awt.Dimension(123, 60));
        btnNotification.setMinimumSize(new java.awt.Dimension(123, 60));
        btnNotification.setPreferredSize(new java.awt.Dimension(123, 60));
        btnNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReadReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRating)
                            .addComponent(lblRatingAmount))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addComponent(lblDeliveryRunnerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEarnings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelilveryRunnerProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(btnLogOut)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(btnLogOut)
                .addGap(10, 10, 10)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(lblRating)
                        .addGap(5, 5, 5)
                        .addComponent(lblRatingAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReadReview, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIcon))
                .addGap(26, 26, 26)
                .addComponent(lblDeliveryRunnerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEarnings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelilveryRunnerProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskActionPerformed
        mainPanel.displayCurrentTask(deliveryRunner);
    }//GEN-LAST:event_btnTaskActionPerformed

    private void btnDelilveryRunnerProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelilveryRunnerProfileActionPerformed
        mainPanel.displayProfile(deliveryRunner);
    }//GEN-LAST:event_btnDelilveryRunnerProfileActionPerformed

    private void btnEarningsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEarningsActionPerformed
        mainPanel.displayEarningsPanel(deliveryRunner);
    }//GEN-LAST:event_btnEarningsActionPerformed

    private void btnReadReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadReviewActionPerformed
        mainPanel.displayDeliveryReviews(deliveryRunner);
    }//GEN-LAST:event_btnReadReviewActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoginFrame login = new LoginFrame();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationActionPerformed
        mainPanel.displayNotification(deliveryRunner);
    }//GEN-LAST:event_btnNotificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryRunnerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryRunnerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryRunnerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryRunnerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DeliveryRunnerMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelilveryRunnerProfile;
    private javax.swing.JButton btnEarnings;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNotification;
    private javax.swing.JButton btnReadReview;
    private javax.swing.JButton btnTask;
    private javax.swing.JLabel lblDeliveryRunnerName;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblRatingAmount;
    private Panel.DeliveryRunner.MainPanel mainPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
