package Frame.UserFrames;

import Frame.Login.LoginFrame;
import User.Vendor;

/**
 *
 * @author KWAN JUN ER TP066265
 */
public class VendorMainPage extends javax.swing.JFrame {
    private Vendor vendor;
   
    public VendorMainPage(Vendor vendor) {
        initComponents();
        this.vendor = vendor;
        lblPhoneNumberInput.setText(vendor.getPhoneNumber());
        lblCuisineInput.setText(vendor.getCuisine());
        lblBusinessNameInput.setText(vendor.getName());
        mainPanel.displayOrder(vendor, 0);
    }
    
    private VendorMainPage() {
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
        lblPhoneNumberInput.setText(vendor.getPhoneNumber());
        lblCuisineInput.setText(vendor.getCuisine());
        lblBusinessNameInput.setText(vendor.getName());
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnFoodMenu = new javax.swing.JButton();
        btnCustomerReviews = new javax.swing.JButton();
        btnRevenueDashboard = new javax.swing.JButton();
        btnNotifications = new javax.swing.JButton();
        lblIcon1 = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblPhoneNumberInput = new javax.swing.JLabel();
        lblCuisine = new javax.swing.JLabel();
        lblCuisineInput = new javax.swing.JLabel();
        lblBusinessNameInput = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        mainPanel = new Panel.Vendor.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendor Main Menu");
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(1200, 600));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 600));

        sidePanel.setMaximumSize(new java.awt.Dimension(250, 600));
        sidePanel.setMinimumSize(new java.awt.Dimension(250, 600));

        btnOrder.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOrder.setIconTextGap(55);
        btnOrder.setRolloverEnabled(false);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnFoodMenu.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnFoodMenu.setText("Food Menu");
        btnFoodMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnFoodMenu.setIconTextGap(55);
        btnFoodMenu.setRolloverEnabled(false);
        btnFoodMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodMenuActionPerformed(evt);
            }
        });

        btnCustomerReviews.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnCustomerReviews.setText("Customer Reviews");
        btnCustomerReviews.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCustomerReviews.setIconTextGap(55);
        btnCustomerReviews.setRolloverEnabled(false);
        btnCustomerReviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerReviewsActionPerformed(evt);
            }
        });

        btnRevenueDashboard.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnRevenueDashboard.setText("Revenue Dashboard");
        btnRevenueDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRevenueDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueDashboardActionPerformed(evt);
            }
        });

        btnNotifications.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnNotifications.setText("Notifications");
        btnNotifications.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificationsActionPerformed(evt);
            }
        });

        lblIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/UserFrames/profileicon.png"))); // NOI18N

        lblPhoneNumber.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblPhoneNumber.setText("Phone Number:");

        lblPhoneNumberInput.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblPhoneNumberInput.setText("{PlaceHolder}");

        lblCuisine.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblCuisine.setText("Cuisine:");

        lblCuisineInput.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblCuisineInput.setText("{PlacehHolder}");

        lblBusinessNameInput.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblBusinessNameInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusinessNameInput.setText("{Insert  Name}");

        btnLogOut.setText("Log Out ");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProfile.setIconTextGap(55);
        btnProfile.setRolloverEnabled(false);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblIcon1)
                        .addGap(8, 8, 8)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNumber)
                            .addComponent(lblPhoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCuisineInput, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblBusinessNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnFoodMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnCustomerReviews, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNotifications, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(btnRevenueDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(btnLogOut)
                .addGap(6, 6, 6)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblIcon1))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(lblPhoneNumber)
                        .addGap(6, 6, 6)
                        .addComponent(lblPhoneNumberInput)
                        .addGap(18, 18, 18)
                        .addComponent(lblCuisine)
                        .addGap(6, 6, 6)
                        .addComponent(lblCuisineInput)))
                .addGap(12, 12, 12)
                .addComponent(lblBusinessNameInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFoodMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomerReviews, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRevenueDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCustomerReviews, btnFoodMenu, btnNotifications, btnOrder, btnProfile, btnRevenueDashboard});

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerReviewsActionPerformed
        mainPanel.displayCustomerReviews(vendor);
    }//GEN-LAST:event_btnCustomerReviewsActionPerformed

    private void btnFoodMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodMenuActionPerformed
        mainPanel.displayFoodMenu(vendor);
    }//GEN-LAST:event_btnFoodMenuActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        mainPanel.displayVendorProfile(vendor);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        mainPanel.displayOrder(vendor, 0);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnRevenueDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueDashboardActionPerformed
        mainPanel.displayRevenueDashboard(vendor);
    }//GEN-LAST:event_btnRevenueDashboardActionPerformed

    private void btnNotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationsActionPerformed
        mainPanel.displayNotifications(vendor);
    }//GEN-LAST:event_btnNotificationsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoginFrame login = new LoginFrame();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendorMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendorMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendorMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendorMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendorMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerReviews;
    private javax.swing.JButton btnFoodMenu;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNotifications;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRevenueDashboard;
    private javax.swing.JLabel lblBusinessNameInput;
    private javax.swing.JLabel lblCuisine;
    private javax.swing.JLabel lblCuisineInput;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberInput;
    private Panel.Vendor.MainPanel mainPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
